server:
  port: 8380

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegister: true
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/  #服务注册地址