server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.100.178.192:3306/xqzx
    username: root
    password: xqzx@123
mybatis:
  type-aliases-package: com.xiqianblog.datamodel