---
server:
  port: 9080

spring:
  profiles: registerserver1

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9090/eureka/
  server:
    enable-self-preservation: false   #关闭自我保护
    eviction-interval-timer-in-ms: 5000   #每隔5秒进行一次服务列表清理

---
server:
  port: 9090

spring:
  profiles: registerserver2

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9080/eureka/
  server:
    enable-self-preservation: false   #关闭自我保护
    eviction-interval-timer-in-ms: 5000   #每隔5秒进行一次服务列表清理